[package]
name = "mist"
version = "0.1.0"
edition = "2024"

[dependencies]
chumsky = "0.10.1"
clap = { version = "4.5.45", features = ["derive"] }
logos = "0.15.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
serde_path_to_error = "0.1.17"
